[package]
name = "psearch"
version = "0.1.0"
authors = ["Alan Du <alanhdu@gmail.com>"]
edition = "2018"

[dependencies]
arr_macro = "0.1"

[dev-dependencies]
criterion = "0.2"
rand = "0.6"

[[bench]]
name = "xfast_set"
harness = false
